### ISSUE TITLE
Couldn't resolve dependencies

### ISSUE THREAD

**Issue by khinephyusin** [jonfryd/ImageClustering#1]
@jonfryd [ERROR] Failed to execute goal on project ImageClustering: Could not resolve dependencies for project dk.impact:ImageClustering:jar:1.0-SNAPSHOT: Could not find artifact fr.inria.axis.clustering:dsom:jar:0.0.1 in osgeo (http://download.osgeo.org/webdav/geotools/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Couldn't download from OSGeo
can u please kindly help?

**Comment by jonfryd** [comment]
Hi @khinephyusin,

Thanks for reporting this. I've updated the README just now.

You need to execute `mvn clean` separately on the first build to execute `maven-install-plugin` which installs the required dependency in question.
